### ISSUE TITLE
Support more fields at AssemblyInfoVersionPatcher task

### ISSUE THREAD

**Issue by haimadrian** [Ullink/gradle-msbuild-plugin#110]
Hi,

Currently, AssemblyInfoVersionPatcher supports customizing those fields:
1. AssemblyVersion
2. AssemblyFileVersion
3. AssemblyInformationalVersion
4. AssemblyDescription

There are additional fields I would like to customize as part of product build:
5. AssemblyTitle
6. AssemblyCompany
7. AssemblyProduct
8. AssemblyCopyright
9. AssemblyTrademark

Is it possible to modify or extend current AssemblyInfoVersionPatcher such that it will get a map as @ Input, where I put all desired fields? 
Declaring additional input members is fine as well

Thank you very much!

**Comment by haimadrian** [comment]
Hi and thanks for the reply.
Let's take for example AssemblyCopyright, where I want to update the year based on current year.
The other fields are required for the assemblies to be updated based on the product that ship them. I have 4 different products shipping the assemblies as a driver, and I want the assembly title, trademark, etc. to get updated according to the product's name.

I could use TokenReplacer to do that, but just thought it could be nice using AssemblyInfoVersionPatcher with a map containing all of the fields I need

**Comment by ngyukman** [comment]
thanks for your clarification, imo adding additional input parameter to AssemblyInfoVersionPatcher is better than a map
