### ISSUE TITLE
Please publish to Gradle Plugins Portal 

### ISSUE THREAD

**Issue by ysb33r** [Ullink/gradle-msbuild-plugin#18]
Here's the detail on what you need to do  - http://plugins.gradle.org/submit.

Using https://github.com/etiennestuder/gradle-plugindev-plugin by @etiennestuder will make your life significantly easier in this regards.
I
f you need help, just shout out.

**Comment by gluck** [comment]
That wasn't quite smooth, but it should be available now, if you want to give it a try !

**Comment by ysb33r** [comment]
It has not appeared on plugins.gradle.org yet, but it looks from bintray like you have loaded the correct information. (When it appears I'll tweet about it).
