### ISSUE TITLE
Warning message: Project XXX found in solution, disabling input/output optimizations

### ISSUE THREAD

**Issue by tekuser** [Ullink/gradle-msbuild-plugin#31]
Hello,

I am using this plugin to build a Visual Studio C++ solution. This solution contains around 15 projects (vcxproj). I want to compile the whole solution so I set the "projectFile" and ignore the "projectName".
When I run gradle (no matter of the task to execute), I receive the warning message:

Project XXX found in solution, disabling input/output optimizations

First, there is a mistake in the message: it should be "Project XXX not found ..." because the code in the resolveProject method of Msbuild.groovy:

projectParsed = allProjects[getProjectName()]
if (projectParsed == null) {
                    parseProject = false
                    logger.warn "Project ${getProjectName()} found in solution, disabling input/output optimizations"
                }

As you can see, the warning is displayed only if the projectName project is not found.

Secondly, msbuild supports the "incremental" build so there is no need of gradle optimisation. So I just would like to disable this warning in the case of a whole solution build. I think that if projectName is not defined (null or empty string) then there is no need to display the warning.

Thanks.

**Comment by gluck** [comment]
Not really a use case I anticipated, but it can't hurt to support it.
Thanks.
