### ISSUE TITLE
C++ Builds

### ISSUE THREAD

**Issue by anasmughal** [Ullink/gradle-msbuild-plugin#61]
Any plans to support C++ builds on windows?

**Comment by gluck** [comment]
Nothing in my plans (no need for it), but this plugin is open to contributions for that to work.
Note that I wouldn't be surprised if there was very little stuff to do for that to happen, this plugin is mostly a sln/*proj parser/wrapper, it doesn't know much about the languages themselves.

Did you give it a try?

**Comment by anasmughal** [comment]
That makes sense... Let me give it a try. Thank you so much for getting back to me.

Sure, I would love to contribute if I make any changes to make it work.

**Comment by anasmughal** [comment]
This plugin worked for our C++ Visual Studio Project. It built the entire solution. Now, I am in the process of setting up a continuous build system using this plugin. I will report back any updates. 

Thank you so much for sharing this plugin.

**Comment by gluck** [comment]
Good news, thanks for sharing!
