### ISSUE TITLE
Add support of msbuild shipped with VS 2017+

### ISSUE THREAD

**Issue by dtretyakov** [Ullink/gradle-msbuild-plugin#75]
In VS 2017 has been changed way to register tools in the system and now each VS installation creates a file in `%ProgramData%\Microsoft\VisualStudio\Packages\_Instances\%installation_id%\state.json`. 

In the `installationPath` we can retrieve a VS installation path and check MsBuild availability in the `MSBuild` directory.

**Comment by gdurand** [comment]
As a workaround for other unforeseen changes like this one, I think the directory of MSBuild could be an optional plugin setting.

**Comment by ngyukman** [comment]
indeed for vs2017+ we need to get the correct msbuild relative to the installed visual studio
we should use https://github.com/Microsoft/vswhere/wiki/Find-MSBuild in order to get the msbuild (at least for windows)

**Comment by ngyukman** [comment]
Released with 2.17
