### ISSUE TITLE
No such property: projects for class: com.ullink.AssemblyInfoVersionPatcher_Decorated

### ISSUE THREAD

**Issue by chazul** [Ullink/gradle-msbuild-plugin#76]
I modified the sample buildscript on your home page and at the bottom there is the following code:

assemblyInfoPatcher {
  ...
  projects = [ 'XZYProject' ]
}

When I looked at 'class AssemblyInfoVersionPatcher', 'fileVersion' and 'version' have a '@Input' but not the 'projects'. Could this be the reason? Or am I doing something wrong?

**Comment by gluck** [comment]
No it shouldn't have such impact AFAIK. Most likely cause is that you're using an earlier version of the plugin when the projects property didn't exist, can you double check ?

**Comment by chazul** [comment]
Yes it was the wrong version. But it was because I copied your example on the main page. Please correct the plugin version in that. The latest I found was 2.14 and it solved the issue.

dependencies {
        classpath "com.ullink.gradle:gradle-msbuild-plugin:2.14"
    }

**Comment by gluck** [comment]
Done, note that 2.16 should be the latest, you can see the changes in the [CHANGELOG](https://github.com/Ullink/gradle-msbuild-plugin/blob/master/CHANGELOG.md)
