### ISSUE TITLE
Use msbuild instead of xbuild on Linux/MacOS

### ISSUE THREAD

**Issue by krisztiankocsis** [Ullink/gradle-msbuild-plugin#84]
Hi!

The current Mono system complains about the usage of xbuild due to deprecation. It also don't support all parameters that are supported by msbuild. Msbuild is the new recommended build tool for Mono.

Pls. consider defaulting to msbuild instead of xbuild on Linux and MacOS.

BTW, I need this feature so I'm willing to help if you give me some starting point.

**Comment by ngyukman** [comment]
Hi @krisztiankocsis 

thanks very much for your help
you may check https://github.com/Ullink/gradle-msbuild-plugin/blob/master/src/main/groovy/com/ullink/XbuildResolver.groovy for how xbuild is resolved currently

perhaps you can add a new LinuxMsbuildResolver and let XbuildResolver as fallback when msbuild is not found

**Comment by Oddley** [comment]
This bug is blocking a project for me. It looks like there is a fix for it that hasn't been released yet. Is that going to be released anytime soon?

**Comment by ngyukman** [comment]
Hi @Oddley the plugin has been released

**Comment by Oddley** [comment]
So fast! Thanks so much!
